#!/bin/bash

echo -e '\n'

echo -e '\t\033[1;96mAliases\t\t\t\033[1;93mDescription\n\t\033[1;97m-------\t\t\t-----------'
echo -e '\t\033[0;96mzconf\t\t\t\033[0;93mZSH Config File'
echo -e '\t\033[0;96mvconf\t\t\t\033[0;93mVIM Config File'
echo -e '\t\033[0;96mtconf\t\t\t\033[0;93mTMUX Config File'
echo -e '\t\033[0;96mvcolors\t\t\t\033[0;93mVIM Theme Colors'
echo -e '\t\033[0;96mrzsh\t\t\t\033[0;93mReload ZSH'
echo -e '\t\033[0;96mrtmux\t\t\t\033[0;93mReload TMUX'
echo -e '\t\033[0;96mrconda\t\t\t\033[0;93mRun Conda'
echo -e '\t\033[0;96mdeda\t\t\t\033[0;93mActivate Dedalus Library'
echo -e '\t\033[0;96mffold\t\t\t\033[0;93mCD to Fortran Folder'
echo -e '\n\t\033[1;96mPath Vars\t\t\033[1;93mPath\n\t\033[1;97m---------\t\t----'
echo -e '\t\033[0;96m$gaussian\t\t\033[0;93m~/Documents/Fluids/gaussian'
echo -e '\n\t\033[1;96mLog Ons\t\t\t\033[1;93mMachine\n\t\033[1;97m-------\t\t\t-------'
echo -e '\t\033[0;96mexpanse\t\t\t\033[0;93mSDSC Expanse Computer'
echo -e '\t\033[0;96mhb\t\t\t\033[0;93mUCSC Hummingbird Computer'
echo -e '\t\033[0;96mgrape\t\t\t\033[0;93mUCSC Grape Computer'


echo -e '\n'
